version: '3.2'
services:

  nginx:
    ports:
    - 80:80
    restart: always
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    restart: always
    environment:
      PHP_IDE_CONFIG: "serverName=Docker-rss"
      APP_ENV: dev
      APP_DEBUG: 1

  php-cli:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./:/var/www
    restart: unless-stopped
    environment:
      APP_ENV: dev
      APP_DEBUG: 1

  postgres:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: rssdb
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  api-postgres:
